# Generated by Django 4.1.1 on 2022-10-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileUpload', '0005_alter_file_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(default='file', max_length=50),
        ),
    ]
