# Generated by Django 4.1.1 on 2022-10-05 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FileUpload', '0008_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_of',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
