# Generated by Django 4.1.1 on 2022-10-07 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FileUpload', '0009_file_file_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
